insert into USERS (USER_ID, USERNAME, PASSWORD, EMAIL, DATE_CREATED, DATE_CHANGED)
values (1, 'john', '$2a$10$C0i7HRcttffXVWXg1xbUsumMUslSL9zjvNB53HpH6hrmNBKNwv3ui', 'john@goodmail.com', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

insert into USERS (USER_ID, USERNAME, PASSWORD, EMAIL, DATE_CREATED, DATE_CHANGED)
values (2, 'frank', '$2a$10$TXpfueRFNadJxnmkceGQVuGAjZ5tjAsPz6Q1vA6V7ik/YsgK4yAiu', 'fank@goodmail.com', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

insert into USERS (USER_ID, USERNAME, PASSWORD, EMAIL, DATE_CREATED, DATE_CHANGED)
values (3, 'linda', '$2a$10$LalbHJgZigrUtBs6cs7cwegUb9422NHVtVoJi2t1f75kNbhaqOns.', 'linda@goodmail.com', CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());


insert into ACCOUNTS (ACCOUNT_NO, USER_ID, DATE_CREATED, DATE_CHANGED)
values ('LT000000000000000001', 1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

insert into ACCOUNTS (ACCOUNT_NO, USER_ID, DATE_CREATED, DATE_CHANGED)
values ('LT000000000000000002', 1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

insert into ACCOUNTS (ACCOUNT_NO, USER_ID, DATE_CREATED, DATE_CHANGED)
values ('LT000000000000000003', 1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

insert into ACCOUNTS (ACCOUNT_NO, USER_ID, DATE_CREATED, DATE_CHANGED)
values ('LT123456789012345678', 2, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

insert into ACCOUNTS (ACCOUNT_NO, USER_ID, DATE_CREATED, DATE_CHANGED)
values ('LT112233445566778899', 2, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

insert into ACCOUNTS (ACCOUNT_NO, USER_ID, DATE_CREATED, DATE_CHANGED)
values ('LT000000000000000004', 3, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());